cache:
  directories:
  - node_modules
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy:prod -- --token ${FIREBASE_TOKEN}
  on:
    branch: master
language: node_js
node_js:
  - "node"
  - "6"
  - "5"
  - "4"
install:
  - npm install -g firebase-tools
